Repository anasm-17/lyrics_transliteration, pull requests merged in 2020-01, with the labels that each got.

#1 is out put ok?
  scraping.ipynb
Labels: data_acquisition

#6 Contributing file
  contributing.md
Labels: documentation

#9 Attention model - data cleaning
  attention-01.ipynb
  data/cmn-eng/_about.txt
  data/cmn-eng/cmn.txt
  nmt_with_attention.ipynb
  scraping.ipynb
Labels: model_development

#12 attention model seems working after re-training
  attention-01.ipynb
Labels: model_development
